### ISSUE TITLE
Is it possible to pause / resume the parsing?

### ISSUE THREAD

**Issue by sebastientromp** [lddubeau/saxes#25] opened 2019-11-13 06:23 UTC
I would like to start parsing the XML, then once a specific element has been reached I would like to pause it, apply some logic to what has already been processed, then resume the parsing once I'm done.

Is it possible to achieve this using saxes?
Or should I first parse the string, split it into chunks, and feed each chunk separately to saxes?

**Comment by lddubeau** [comment] 2019-11-13 23:52
While the code in an event handler is executing, parsing is effectively paused. Parsing does not resume until the event handler returns. But I don't think I'm telling you something you did not already know, and this probably does not help you. 

Also, the fact that parsing does not resume until the event handler returns does not help if what you want to do is pause parsing until an asynchronous operation is over.

As we speak, the only other way to pause parsing would be, as you suggested, to break the XML document into chunks that are then passed to saxes in multiple `write` calls. Parsing is effectively paused between the `write` calls. Note that saxes does not require that you cut your document in any specific way. You can cut anywhere you want. You can cut on all ``<`` character, every 100 character, or even feed saxes character by character if you want. That's all up to you.

**Comment by sebastientromp** [comment] 2019-11-14 14:06
Thanks for the reply!
It's really nice that I can split the input XML however I want, it should work perfectly for me that way :)
Thanks again

**Comment by lddubeau** [comment] 2019-11-14 14:47
Looks like the issue is resolved. So I'm going to close this. We can reopen if needed, or if you run into a specific failure, a new issue can be raised.

**Closed by lddubeau** 2019-11-14 14:47 UTC
